# Created by Topology-Converter v3.3
#    using topology data from: examples/reference_topology_virtualbox.dot
#    using definition data from: examples/reference_topology_virtualbox.def
#    NOTE: in order to use this Vagrantfile you will need:
#        -Virtualbox installed: https://www.virtualbox.org/wiki/Downloads
#        -Vagrant(v1.7+) installed: http://www.vagrantup.com/downloads
#        -Cumulus Plugin for Vagrant installed: $ vagrant plugin install vagrant-cumulus
#        -the "helper_scripts" directory that comes packaged with topology-converter.py
Vagrant.configure("2") do |config|
  ##### GLOBAL OPTIONS #####

  config.vm.provider "virtualbox" do |v|
    v.gui=false
  end
  ##### DEFINE VMs #####
  ##### DEFINE VM for oob-mgmt-server #####
  config.vm.define "oob-mgmt-server" do |oob_mgmt_server|
      oob_mgmt_server.vm.provider "virtualbox" do |v|
        v.name = "oob-mgmt-server"
        v.memory = 400
      end
      oob_mgmt_server.vm.hostname = "oob-mgmt-server"
      oob_mgmt_server.vm.box = "boxcutter/ubuntu1404"

          # Local_Interface: eth1 Topology_File_Line(41): "oob-mgmt-server":"eth1" -- "oob-mgmt-switch":"swp1"
          oob_mgmt_server.vm.network "private_network", virtualbox__intnet: 'net41', auto_config: false

      # Disabling the default synced folder
      oob_mgmt_server.vm.synced_folder ".", "/vagrant", disabled: true

      # UBUNTU DEVICES ONLY: Shorten Boot Process - remove "Wait for Network"
      oob_mgmt_server.vm.provision :shell , inline: "sudo sed -i 's/sleep [0-9]*/sleep 1/' /etc/init/failsafe.conf"

      # Run Any Extra Config
      oob_mgmt_server.vm.provision :shell , path: "./helper_scripts/1st_device_config.sh"

      # Apply the interface re-map
      oob_mgmt_server.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      oob_mgmt_server.vm.provision "file", source: "./helper_scripts/autogenerated/oob-mgmt-server_remap_eth", destination: "/home/vagrant/remap_eth"
      oob_mgmt_server.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      oob_mgmt_server.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      oob_mgmt_server.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      oob_mgmt_server.vm.provision :shell , inline: "sudo sed -i '/exit 0/d' /etc/rc.local "
      oob_mgmt_server.vm.provision :shell , inline: "sudo echo '/etc/init.d/rename_eth_swp start' >> /etc/rc.local "
      oob_mgmt_server.vm.provision :shell , inline: "sudo echo 'exit 0' >> /etc/rc.local "
      oob_mgmt_server.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      oob_mgmt_server.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
      end

      oob_mgmt_server.vm.provision "ansible" do |ansible|
        ansible.playbook = "./ccw-wbenchvm-ansible/site.yml"
        ansible.extra_vars = {  ravello: true,
                                do_ztp: false,
                                create_key: false,
                                wbench_hostname: 'oob-mgmt-server',
                                wbench_password: "X/1dWAy895j9TuMfJkjnXSvYKSJr1Ny0'",
                                wbench_hosts: {
                                    leaf01: {
                                        ip: '192.168.0.11',
                                        mac: 'a0:00:00:00:00:11'},
                                    leaf02: {
                                        ip: '192.168.0.12',
                                        mac: 'a0:00:00:00:00:12'},
                                    leaf03: {
                                        ip: '192.168.0.13',
                                        mac: 'a0:00:00:00:00:13'},
                                    leaf04: {
                                        ip: '192.168.0.14',
                                        mac: 'a0:00:00:00:00:14'},
                                    spine01: {
                                        ip: '192.168.0.21',
                                        mac: 'a0:00:00:00:00:21'},
                                    spine02: {
                                        ip: '192.168.0.22',
                                        mac: 'a0:00:00:00:00:22'},
                                    server01: {
                                        ip: '192.168.0.31',
                                        mac: 'a0:00:00:00:00:31'},
                                    server02: {
                                        ip: '192.168.0.32',
                                        mac: 'a0:00:00:00:00:32'},
                                    server03: {
                                        ip: '192.168.0.33',
                                        mac: 'a0:00:00:00:00:33'},
                                    server04: {
                                        ip: '192.168.0.34',
                                        mac: 'a0:00:00:00:00:34'},
                                    exit01: {
                                        ip: '192.168.0.41',
                                        mac: 'a0:00:00:00:00:41'},
                                    exit02: {
                                        ip: '192.168.0.42',
                                        mac: 'a0:00:00:00:00:42'}
                            }}
      end
  end

    ##### DEFINE VM for oob-mgmt-switch #####
    config.vm.define "oob-mgmt-switch" do |oob_mgmt_switch|
        oob_mgmt_switch.vm.provider "virtualbox" do |v|
          v.name = "oob-mgmt-switch"
          v.memory = 200
        end
        oob_mgmt_switch.vm.hostname = "oob-mgmt-switch"
        oob_mgmt_switch.vm.box = "CumulusCommunity/cumulus-vx"

            # Local_Interface: swp1 Topology_File_Line(41): "oob-mgmt-server":"eth1" -- "oob-mgmt-switch":"swp1"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net41', auto_config: false

            # Local_Interface: swp2 Topology_File_Line(42): "server01":"eth0" -- "oob-mgmt-switch":"swp2"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net42', auto_config: false

            # Local_Interface: swp3 Topology_File_Line(43): "server02":"eth0" -- "oob-mgmt-switch":"swp3"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net43', auto_config: false

            # Local_Interface: swp4 Topology_File_Line(44): "server03":"eth0" -- "oob-mgmt-switch":"swp4"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net44', auto_config: false

            # Local_Interface: swp5 Topology_File_Line(45): "server04":"eth0" -- "oob-mgmt-switch":"swp5"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net45', auto_config: false

            # Local_Interface: swp6 Topology_File_Line(46): "leaf01":"eth0" -- "oob-mgmt-switch":"swp6"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net46', auto_config: false

            # Local_Interface: swp7 Topology_File_Line(47): "leaf02":"eth0" -- "oob-mgmt-switch":"swp7"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net47', auto_config: false

            # Local_Interface: swp8 Topology_File_Line(48): "leaf03":"eth0" -- "oob-mgmt-switch":"swp8"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net48', auto_config: false

            # Local_Interface: swp9 Topology_File_Line(49): "leaf04":"eth0" -- "oob-mgmt-switch":"swp9"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net49', auto_config: false

            # Local_Interface: swp10 Topology_File_Line(50): "spine01":"eth0" -- "oob-mgmt-switch":"swp10"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net50', auto_config: false

            # Local_Interface: swp11 Topology_File_Line(51): "spine02":"eth0" -- "oob-mgmt-switch":"swp11"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net51', auto_config: false

            # Local_Interface: swp12 Topology_File_Line(52): "exit01":"eth0" -- "oob-mgmt-switch":"swp12"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net52', auto_config: false

            # Local_Interface: swp13 Topology_File_Line(53): "exit02":"eth0" -- "oob-mgmt-switch":"swp13"
            oob_mgmt_switch.vm.network "private_network", virtualbox__intnet: 'net53', auto_config: false

        # Disabling the default synced folder
        oob_mgmt_switch.vm.synced_folder ".", "/vagrant", disabled: true

        # Run Any Extra Config
        oob_mgmt_switch.vm.provision :shell , path: "./helper_scripts/2nd_device_config.sh"

        # Apply the interface re-map
        oob_mgmt_switch.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
        oob_mgmt_switch.vm.provision "file", source: "./helper_scripts/autogenerated/oob-mgmt-switch_remap_eth", destination: "/home/vagrant/remap_eth"
        oob_mgmt_switch.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
        oob_mgmt_switch.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
        oob_mgmt_switch.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
        oob_mgmt_switch.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

        oob_mgmt_switch.vm.provider "virtualbox" do |vbox|
          vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc11', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc12', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc13', 'allow-vms']
          vbox.customize ['modifyvm', :id, '--nicpromisc14', 'allow-vms']
        end
    end

  ##### DEFINE VM for server01 #####
  config.vm.define "server01" do |server01|
      server01.vm.provider "virtualbox" do |v|
        v.name = "server01"
        v.memory = 400
      end
      server01.vm.hostname = "server01"
      server01.vm.box = "boxcutter/ubuntu1404"

          # Local_Interface: eth0 Topology_File_Line(42): "server01":"eth0" -- "oob-mgmt-switch":"swp2"
          server01.vm.network "private_network", virtualbox__intnet: 'net42', auto_config: false, :mac => "A00000000031"

          # Local_Interface: eth1 Topology_File_Line(15): "server01":"eth1" -- "leaf01":"swp1"
          server01.vm.network "private_network", virtualbox__intnet: 'net15', auto_config: false

          # Local_Interface: eth2 Topology_File_Line(16): "server01":"eth2" -- "leaf02":"swp1"
          server01.vm.network "private_network", virtualbox__intnet: 'net16', auto_config: false

      # Disabling the default synced folder
      server01.vm.synced_folder ".", "/vagrant", disabled: true

      # UBUNTU DEVICES ONLY: Shorten Boot Process - remove "Wait for Network"
      server01.vm.provision :shell , inline: "sudo sed -i 's/sleep [0-9]*/sleep 1/' /etc/init/failsafe.conf"

      # Run Any Extra Config
      server01.vm.provision :shell , path: "./helper_scripts/extra_server_config.sh"

      # Apply the interface re-map
      server01.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      server01.vm.provision "file", source: "./helper_scripts/autogenerated/server01_remap_eth", destination: "/home/vagrant/remap_eth"
      server01.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      server01.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      server01.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      server01.vm.provision :shell , inline: "sudo sed -i '/exit 0/d' /etc/rc.local "
      server01.vm.provision :shell , inline: "sudo echo '/etc/init.d/rename_eth_swp start' >> /etc/rc.local "
      server01.vm.provision :shell , inline: "sudo echo 'exit 0' >> /etc/rc.local "
      server01.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      server01.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
      end

      # Run Postconfig
      server01.vm.provision :shell , path: "./helper_scripts/extra_server_post_config.sh"
  end

  ##### DEFINE VM for server02 #####
  config.vm.define "server02" do |server02|
      server02.vm.provider "virtualbox" do |v|
        v.name = "server02"
        v.memory = 400
      end
      server02.vm.hostname = "server02"
      server02.vm.box = "boxcutter/ubuntu1404"

          # Local_Interface: eth0 Topology_File_Line(43): "server02":"eth0" -- "oob-mgmt-switch":"swp3"
          server02.vm.network "private_network", virtualbox__intnet: 'net43', auto_config: false, :mac => "A00000000032"

          # Local_Interface: eth1 Topology_File_Line(17): "server02":"eth1" -- "leaf01":"swp2"
          server02.vm.network "private_network", virtualbox__intnet: 'net17', auto_config: false

          # Local_Interface: eth2 Topology_File_Line(18): "server02":"eth2" -- "leaf02":"swp2"
          server02.vm.network "private_network", virtualbox__intnet: 'net18', auto_config: false

      # Disabling the default synced folder
      server02.vm.synced_folder ".", "/vagrant", disabled: true

      # UBUNTU DEVICES ONLY: Shorten Boot Process - remove "Wait for Network"
      server02.vm.provision :shell , inline: "sudo sed -i 's/sleep [0-9]*/sleep 1/' /etc/init/failsafe.conf"

      # Run Any Extra Config
      server02.vm.provision :shell , path: "./helper_scripts/extra_server_config.sh"

      # Apply the interface re-map
      server02.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      server02.vm.provision "file", source: "./helper_scripts/autogenerated/server02_remap_eth", destination: "/home/vagrant/remap_eth"
      server02.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      server02.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      server02.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      server02.vm.provision :shell , inline: "sudo sed -i '/exit 0/d' /etc/rc.local "
      server02.vm.provision :shell , inline: "sudo echo '/etc/init.d/rename_eth_swp start' >> /etc/rc.local "
      server02.vm.provision :shell , inline: "sudo echo 'exit 0' >> /etc/rc.local "
      server02.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      server02.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
      end

      # Run Postconfig
      server02.vm.provision :shell , path: "./helper_scripts/extra_server_post_config.sh"
  end

  ##### DEFINE VM for server03 #####
  config.vm.define "server03" do |server03|
      server03.vm.provider "virtualbox" do |v|
        v.name = "server03"
        v.memory = 400
      end
      server03.vm.hostname = "server03"
      server03.vm.box = "boxcutter/ubuntu1404"

          # Local_Interface: eth0 Topology_File_Line(44): "server03":"eth0" -- "oob-mgmt-switch":"swp4"
          server03.vm.network "private_network", virtualbox__intnet: 'net44', auto_config: false, :mac => "A00000000033"

          # Local_Interface: eth1 Topology_File_Line(19): "server03":"eth1" -- "leaf03":"swp1"
          server03.vm.network "private_network", virtualbox__intnet: 'net19', auto_config: false

          # Local_Interface: eth2 Topology_File_Line(20): "server03":"eth2" -- "leaf04":"swp1"
          server03.vm.network "private_network", virtualbox__intnet: 'net20', auto_config: false

      # Disabling the default synced folder
      server03.vm.synced_folder ".", "/vagrant", disabled: true

      # UBUNTU DEVICES ONLY: Shorten Boot Process - remove "Wait for Network"
      server03.vm.provision :shell , inline: "sudo sed -i 's/sleep [0-9]*/sleep 1/' /etc/init/failsafe.conf"

      # Run Any Extra Config
      server03.vm.provision :shell , path: "./helper_scripts/extra_server_config.sh"

      # Apply the interface re-map
      server03.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      server03.vm.provision "file", source: "./helper_scripts/autogenerated/server03_remap_eth", destination: "/home/vagrant/remap_eth"
      server03.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      server03.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      server03.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      server03.vm.provision :shell , inline: "sudo sed -i '/exit 0/d' /etc/rc.local "
      server03.vm.provision :shell , inline: "sudo echo '/etc/init.d/rename_eth_swp start' >> /etc/rc.local "
      server03.vm.provision :shell , inline: "sudo echo 'exit 0' >> /etc/rc.local "
      server03.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      server03.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
      end

      # Run Postconfig
      server03.vm.provision :shell , path: "./helper_scripts/extra_server_post_config.sh"
  end

  ##### DEFINE VM for server04 #####
  config.vm.define "server04" do |server04|
      server04.vm.provider "virtualbox" do |v|
        v.name = "server04"
        v.memory = 400
      end
      server04.vm.hostname = "server04"
      server04.vm.box = "boxcutter/ubuntu1404"

          # Local_Interface: eth0 Topology_File_Line(45): "server04":"eth0" -- "oob-mgmt-switch":"swp5"
          server04.vm.network "private_network", virtualbox__intnet: 'net45', auto_config: false, :mac => "A00000000034"

          # Local_Interface: eth1 Topology_File_Line(21): "server04":"eth1" -- "leaf03":"swp2"
          server04.vm.network "private_network", virtualbox__intnet: 'net21', auto_config: false

          # Local_Interface: eth2 Topology_File_Line(22): "server04":"eth2" -- "leaf04":"swp2"
          server04.vm.network "private_network", virtualbox__intnet: 'net22', auto_config: false

      # Disabling the default synced folder
      server04.vm.synced_folder ".", "/vagrant", disabled: true

      # UBUNTU DEVICES ONLY: Shorten Boot Process - remove "Wait for Network"
      server04.vm.provision :shell , inline: "sudo sed -i 's/sleep [0-9]*/sleep 1/' /etc/init/failsafe.conf"

      # Run Any Extra Config
      server04.vm.provision :shell , path: "./helper_scripts/extra_server_config.sh"

      # Apply the interface re-map
      server04.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      server04.vm.provision "file", source: "./helper_scripts/autogenerated/server04_remap_eth", destination: "/home/vagrant/remap_eth"
      server04.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      server04.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      server04.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      server04.vm.provision :shell , inline: "sudo sed -i '/exit 0/d' /etc/rc.local "
      server04.vm.provision :shell , inline: "sudo echo '/etc/init.d/rename_eth_swp start' >> /etc/rc.local "
      server04.vm.provision :shell , inline: "sudo echo 'exit 0' >> /etc/rc.local "
      server04.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      server04.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
      end

      # Run Postconfig
      server04.vm.provision :shell , path: "./helper_scripts/extra_server_post_config.sh"
  end

  ##### DEFINE VM for leaf01 #####
  config.vm.define "leaf01" do |leaf01|
      leaf01.vm.provider "virtualbox" do |v|
        v.name = "leaf01"
        v.memory = 200
      end
      leaf01.vm.hostname = "leaf01"
      leaf01.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(46): "leaf01":"eth0" -- "oob-mgmt-switch":"swp6"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net46', auto_config: false, :mac => "A00000000011"

          # Local_Interface: swp1 Topology_File_Line(15): "server01":"eth1" -- "leaf01":"swp1"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net15', auto_config: false

          # Local_Interface: swp2 Topology_File_Line(17): "server02":"eth1" -- "leaf01":"swp2"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net17', auto_config: false

          # Local_Interface: swp45 Topology_File_Line(33): "leaf01":"swp45" -- "leaf01":"swp46"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net33', auto_config: false

          # Local_Interface: swp46 Topology_File_Line(33): "leaf01":"swp45" -- "leaf01":"swp46"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net33', auto_config: false

          # Local_Interface: swp47 Topology_File_Line(34): "leaf01":"swp47" -- "leaf01":"swp48"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net34', auto_config: false

          # Local_Interface: swp48 Topology_File_Line(34): "leaf01":"swp47" -- "leaf01":"swp48"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net34', auto_config: false

          # Local_Interface: swp49 Topology_File_Line(9): "leaf01":"swp49" -- "leaf02":"swp49"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net9', auto_config: false

          # Local_Interface: swp50 Topology_File_Line(10): "leaf01":"swp50" -- "leaf02":"swp50"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net10', auto_config: false

          # Local_Interface: swp51 Topology_File_Line(1): "leaf01":"swp51" -- "spine01":"swp1"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net1', auto_config: false

          # Local_Interface: swp52 Topology_File_Line(5): "leaf01":"swp52" -- "spine02":"swp1"
          leaf01.vm.network "private_network", virtualbox__intnet: 'net5', auto_config: false

      # Disabling the default synced folder
      leaf01.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      leaf01.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      leaf01.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      leaf01.vm.provision "file", source: "./helper_scripts/autogenerated/leaf01_remap_eth", destination: "/home/vagrant/remap_eth"
      leaf01.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      leaf01.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      leaf01.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      leaf01.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      leaf01.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc11', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc12', 'allow-vms']
      end

      # Run Postconfig
      leaf01.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

  ##### DEFINE VM for leaf02 #####
  config.vm.define "leaf02" do |leaf02|
      leaf02.vm.provider "virtualbox" do |v|
        v.name = "leaf02"
        v.memory = 200
      end
      leaf02.vm.hostname = "leaf02"
      leaf02.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(47): "leaf02":"eth0" -- "oob-mgmt-switch":"swp7"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net47', auto_config: false, :mac => "A00000000012"

          # Local_Interface: swp1 Topology_File_Line(16): "server01":"eth2" -- "leaf02":"swp1"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net16', auto_config: false

          # Local_Interface: swp2 Topology_File_Line(18): "server02":"eth2" -- "leaf02":"swp2"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net18', auto_config: false

          # Local_Interface: swp45 Topology_File_Line(35): "leaf02":"swp45" -- "leaf02":"swp46"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net35', auto_config: false

          # Local_Interface: swp46 Topology_File_Line(35): "leaf02":"swp45" -- "leaf02":"swp46"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net35', auto_config: false

          # Local_Interface: swp47 Topology_File_Line(36): "leaf02":"swp47" -- "leaf02":"swp48"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net36', auto_config: false

          # Local_Interface: swp48 Topology_File_Line(36): "leaf02":"swp47" -- "leaf02":"swp48"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net36', auto_config: false

          # Local_Interface: swp49 Topology_File_Line(9): "leaf01":"swp49" -- "leaf02":"swp49"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net9', auto_config: false

          # Local_Interface: swp50 Topology_File_Line(10): "leaf01":"swp50" -- "leaf02":"swp50"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net10', auto_config: false

          # Local_Interface: swp51 Topology_File_Line(2): "leaf02":"swp51" -- "spine01":"swp2"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net2', auto_config: false

          # Local_Interface: swp52 Topology_File_Line(6): "leaf02":"swp52" -- "spine02":"swp2"
          leaf02.vm.network "private_network", virtualbox__intnet: 'net6', auto_config: false

      # Disabling the default synced folder
      leaf02.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      leaf02.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      leaf02.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      leaf02.vm.provision "file", source: "./helper_scripts/autogenerated/leaf02_remap_eth", destination: "/home/vagrant/remap_eth"
      leaf02.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      leaf02.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      leaf02.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      leaf02.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      leaf02.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc11', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc12', 'allow-vms']
      end

      # Run Postconfig
      leaf02.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

  ##### DEFINE VM for leaf03 #####
  config.vm.define "leaf03" do |leaf03|
      leaf03.vm.provider "virtualbox" do |v|
        v.name = "leaf03"
        v.memory = 200
      end
      leaf03.vm.hostname = "leaf03"
      leaf03.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(48): "leaf03":"eth0" -- "oob-mgmt-switch":"swp8"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net48', auto_config: false, :mac => "A00000000013"

          # Local_Interface: swp1 Topology_File_Line(19): "server03":"eth1" -- "leaf03":"swp1"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net19', auto_config: false

          # Local_Interface: swp2 Topology_File_Line(21): "server04":"eth1" -- "leaf03":"swp2"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net21', auto_config: false

          # Local_Interface: swp45 Topology_File_Line(37): "leaf03":"swp45" -- "leaf03":"swp46"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net37', auto_config: false

          # Local_Interface: swp46 Topology_File_Line(37): "leaf03":"swp45" -- "leaf03":"swp46"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net37', auto_config: false

          # Local_Interface: swp47 Topology_File_Line(38): "leaf03":"swp47" -- "leaf03":"swp48"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net38', auto_config: false

          # Local_Interface: swp48 Topology_File_Line(38): "leaf03":"swp47" -- "leaf03":"swp48"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net38', auto_config: false

          # Local_Interface: swp49 Topology_File_Line(11): "leaf03":"swp49" -- "leaf04":"swp49"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net11', auto_config: false

          # Local_Interface: swp50 Topology_File_Line(12): "leaf03":"swp50" -- "leaf04":"swp50"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net12', auto_config: false

          # Local_Interface: swp51 Topology_File_Line(3): "leaf03":"swp51" -- "spine01":"swp3"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net3', auto_config: false

          # Local_Interface: swp52 Topology_File_Line(7): "leaf03":"swp52" -- "spine02":"swp3"
          leaf03.vm.network "private_network", virtualbox__intnet: 'net7', auto_config: false

      # Disabling the default synced folder
      leaf03.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      leaf03.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      leaf03.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      leaf03.vm.provision "file", source: "./helper_scripts/autogenerated/leaf03_remap_eth", destination: "/home/vagrant/remap_eth"
      leaf03.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      leaf03.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      leaf03.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      leaf03.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      leaf03.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc11', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc12', 'allow-vms']
      end

      # Run Postconfig
      leaf03.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

  ##### DEFINE VM for leaf04 #####
  config.vm.define "leaf04" do |leaf04|
      leaf04.vm.provider "virtualbox" do |v|
        v.name = "leaf04"
        v.memory = 200
      end
      leaf04.vm.hostname = "leaf04"
      leaf04.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(49): "leaf04":"eth0" -- "oob-mgmt-switch":"swp9"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net49', auto_config: false, :mac => "A00000000014"

          # Local_Interface: swp1 Topology_File_Line(20): "server03":"eth2" -- "leaf04":"swp1"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net20', auto_config: false

          # Local_Interface: swp2 Topology_File_Line(22): "server04":"eth2" -- "leaf04":"swp2"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net22', auto_config: false

          # Local_Interface: swp45 Topology_File_Line(39): "leaf04":"swp45" -- "leaf04":"swp46"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net39', auto_config: false

          # Local_Interface: swp46 Topology_File_Line(39): "leaf04":"swp45" -- "leaf04":"swp46"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net39', auto_config: false

          # Local_Interface: swp47 Topology_File_Line(40): "leaf04":"swp47" -- "leaf04":"swp48"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net40', auto_config: false

          # Local_Interface: swp48 Topology_File_Line(40): "leaf04":"swp47" -- "leaf04":"swp48"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net40', auto_config: false

          # Local_Interface: swp49 Topology_File_Line(11): "leaf03":"swp49" -- "leaf04":"swp49"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net11', auto_config: false

          # Local_Interface: swp50 Topology_File_Line(12): "leaf03":"swp50" -- "leaf04":"swp50"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net12', auto_config: false

          # Local_Interface: swp51 Topology_File_Line(4): "leaf04":"swp51" -- "spine01":"swp4"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net4', auto_config: false

          # Local_Interface: swp52 Topology_File_Line(8): "leaf04":"swp52" -- "spine02":"swp4"
          leaf04.vm.network "private_network", virtualbox__intnet: 'net8', auto_config: false

      # Disabling the default synced folder
      leaf04.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      leaf04.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      leaf04.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      leaf04.vm.provision "file", source: "./helper_scripts/autogenerated/leaf04_remap_eth", destination: "/home/vagrant/remap_eth"
      leaf04.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      leaf04.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      leaf04.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      leaf04.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      leaf04.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc11', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc12', 'allow-vms']
      end

      # Run Postconfig
      leaf04.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

  ##### DEFINE VM for spine01 #####
  config.vm.define "spine01" do |spine01|
      spine01.vm.provider "virtualbox" do |v|
        v.name = "spine01"
        v.memory = 200
      end
      spine01.vm.hostname = "spine01"
      spine01.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(50): "spine01":"eth0" -- "oob-mgmt-switch":"swp10"
          spine01.vm.network "private_network", virtualbox__intnet: 'net50', auto_config: false, :mac => "A00000000021"

          # Local_Interface: swp1 Topology_File_Line(1): "leaf01":"swp51" -- "spine01":"swp1"
          spine01.vm.network "private_network", virtualbox__intnet: 'net1', auto_config: false

          # Local_Interface: swp2 Topology_File_Line(2): "leaf02":"swp51" -- "spine01":"swp2"
          spine01.vm.network "private_network", virtualbox__intnet: 'net2', auto_config: false

          # Local_Interface: swp3 Topology_File_Line(3): "leaf03":"swp51" -- "spine01":"swp3"
          spine01.vm.network "private_network", virtualbox__intnet: 'net3', auto_config: false

          # Local_Interface: swp4 Topology_File_Line(4): "leaf04":"swp51" -- "spine01":"swp4"
          spine01.vm.network "private_network", virtualbox__intnet: 'net4', auto_config: false

          # Local_Interface: swp29 Topology_File_Line(25): "exit02":"swp51" -- "spine01":"swp29"
          spine01.vm.network "private_network", virtualbox__intnet: 'net25', auto_config: false

          # Local_Interface: swp30 Topology_File_Line(23): "exit01":"swp51" -- "spine01":"swp30"
          spine01.vm.network "private_network", virtualbox__intnet: 'net23', auto_config: false

          # Local_Interface: swp31 Topology_File_Line(13): "spine01":"swp31" -- "spine02":"swp31"
          spine01.vm.network "private_network", virtualbox__intnet: 'net13', auto_config: false

          # Local_Interface: swp32 Topology_File_Line(14): "spine01":"swp32" -- "spine02":"swp32"
          spine01.vm.network "private_network", virtualbox__intnet: 'net14', auto_config: false

      # Disabling the default synced folder
      spine01.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      spine01.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      spine01.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      spine01.vm.provision "file", source: "./helper_scripts/autogenerated/spine01_remap_eth", destination: "/home/vagrant/remap_eth"
      spine01.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      spine01.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      spine01.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      spine01.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      spine01.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
      end

      # Run Postconfig
      spine01.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

  ##### DEFINE VM for spine02 #####
  config.vm.define "spine02" do |spine02|
      spine02.vm.provider "virtualbox" do |v|
        v.name = "spine02"
        v.memory = 200
      end
      spine02.vm.hostname = "spine02"
      spine02.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(51): "spine02":"eth0" -- "oob-mgmt-switch":"swp11"
          spine02.vm.network "private_network", virtualbox__intnet: 'net51', auto_config: false, :mac => "A00000000022"

          # Local_Interface: swp1 Topology_File_Line(5): "leaf01":"swp52" -- "spine02":"swp1"
          spine02.vm.network "private_network", virtualbox__intnet: 'net5', auto_config: false

          # Local_Interface: swp2 Topology_File_Line(6): "leaf02":"swp52" -- "spine02":"swp2"
          spine02.vm.network "private_network", virtualbox__intnet: 'net6', auto_config: false

          # Local_Interface: swp3 Topology_File_Line(7): "leaf03":"swp52" -- "spine02":"swp3"
          spine02.vm.network "private_network", virtualbox__intnet: 'net7', auto_config: false

          # Local_Interface: swp4 Topology_File_Line(8): "leaf04":"swp52" -- "spine02":"swp4"
          spine02.vm.network "private_network", virtualbox__intnet: 'net8', auto_config: false

          # Local_Interface: swp29 Topology_File_Line(26): "exit02":"swp52" -- "spine02":"swp29"
          spine02.vm.network "private_network", virtualbox__intnet: 'net26', auto_config: false

          # Local_Interface: swp30 Topology_File_Line(24): "exit01":"swp52" -- "spine02":"swp30"
          spine02.vm.network "private_network", virtualbox__intnet: 'net24', auto_config: false

          # Local_Interface: swp31 Topology_File_Line(13): "spine01":"swp31" -- "spine02":"swp31"
          spine02.vm.network "private_network", virtualbox__intnet: 'net13', auto_config: false

          # Local_Interface: swp32 Topology_File_Line(14): "spine01":"swp32" -- "spine02":"swp32"
          spine02.vm.network "private_network", virtualbox__intnet: 'net14', auto_config: false

      # Disabling the default synced folder
      spine02.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      spine02.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      spine02.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      spine02.vm.provision "file", source: "./helper_scripts/autogenerated/spine02_remap_eth", destination: "/home/vagrant/remap_eth"
      spine02.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      spine02.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      spine02.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      spine02.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      spine02.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
      end

      # Run Postconfig
      spine02.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

  ##### DEFINE VM for exit01 #####
  config.vm.define "exit01" do |exit01|
      exit01.vm.provider "virtualbox" do |v|
        v.name = "exit01"
        v.memory = 200
      end
      exit01.vm.hostname = "exit01"
      exit01.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(52): "exit01":"eth0" -- "oob-mgmt-switch":"swp12"
          exit01.vm.network "private_network", virtualbox__intnet: 'net52', auto_config: false, :mac => "A00000000041"

          # Local_Interface: swp45 Topology_File_Line(29): "exit01":"swp45" -- "exit01":"swp46"
          exit01.vm.network "private_network", virtualbox__intnet: 'net29', auto_config: false

          # Local_Interface: swp46 Topology_File_Line(29): "exit01":"swp45" -- "exit01":"swp46"
          exit01.vm.network "private_network", virtualbox__intnet: 'net29', auto_config: false

          # Local_Interface: swp47 Topology_File_Line(30): "exit01":"swp47" -- "exit01":"swp48"
          exit01.vm.network "private_network", virtualbox__intnet: 'net30', auto_config: false

          # Local_Interface: swp48 Topology_File_Line(30): "exit01":"swp47" -- "exit01":"swp48"
          exit01.vm.network "private_network", virtualbox__intnet: 'net30', auto_config: false

          # Local_Interface: swp49 Topology_File_Line(27): "exit01":"swp49" -- "exit01":"swp49"
          exit01.vm.network "private_network", virtualbox__intnet: 'net27', auto_config: false

          # Local_Interface: swp49 Topology_File_Line(27): "exit01":"swp49" -- "exit01":"swp49"
          exit01.vm.network "private_network", virtualbox__intnet: 'net27', auto_config: false

          # Local_Interface: swp51 Topology_File_Line(23): "exit01":"swp51" -- "spine01":"swp30"
          exit01.vm.network "private_network", virtualbox__intnet: 'net23', auto_config: false

          # Local_Interface: swp52 Topology_File_Line(24): "exit01":"swp52" -- "spine02":"swp30"
          exit01.vm.network "private_network", virtualbox__intnet: 'net24', auto_config: false

      # Disabling the default synced folder
      exit01.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      exit01.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      exit01.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      exit01.vm.provision "file", source: "./helper_scripts/autogenerated/exit01_remap_eth", destination: "/home/vagrant/remap_eth"
      exit01.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      exit01.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      exit01.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      exit01.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      exit01.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
      end

      # Run Postconfig
      exit01.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

  ##### DEFINE VM for exit02 #####
  config.vm.define "exit02" do |exit02|
      exit02.vm.provider "virtualbox" do |v|
        v.name = "exit02"
        v.memory = 200
      end
      exit02.vm.hostname = "exit02"
      exit02.vm.box = "CumulusCommunity/cumulus-vx"

          # Local_Interface: eth0 Topology_File_Line(53): "exit02":"eth0" -- "oob-mgmt-switch":"swp13"
          exit02.vm.network "private_network", virtualbox__intnet: 'net53', auto_config: false, :mac => "A00000000042"

          # Local_Interface: swp45 Topology_File_Line(31): "exit02":"swp45" -- "exit02":"swp46"
          exit02.vm.network "private_network", virtualbox__intnet: 'net31', auto_config: false

          # Local_Interface: swp46 Topology_File_Line(31): "exit02":"swp45" -- "exit02":"swp46"
          exit02.vm.network "private_network", virtualbox__intnet: 'net31', auto_config: false

          # Local_Interface: swp47 Topology_File_Line(32): "exit02":"swp47" -- "exit02":"swp48"
          exit02.vm.network "private_network", virtualbox__intnet: 'net32', auto_config: false

          # Local_Interface: swp48 Topology_File_Line(32): "exit02":"swp47" -- "exit02":"swp48"
          exit02.vm.network "private_network", virtualbox__intnet: 'net32', auto_config: false

          # Local_Interface: swp50 Topology_File_Line(28): "exit02":"swp50" -- "exit02":"swp50"
          exit02.vm.network "private_network", virtualbox__intnet: 'net28', auto_config: false

          # Local_Interface: swp50 Topology_File_Line(28): "exit02":"swp50" -- "exit02":"swp50"
          exit02.vm.network "private_network", virtualbox__intnet: 'net28', auto_config: false

          # Local_Interface: swp51 Topology_File_Line(25): "exit02":"swp51" -- "spine01":"swp29"
          exit02.vm.network "private_network", virtualbox__intnet: 'net25', auto_config: false

          # Local_Interface: swp52 Topology_File_Line(26): "exit02":"swp52" -- "spine02":"swp29"
          exit02.vm.network "private_network", virtualbox__intnet: 'net26', auto_config: false

      # Disabling the default synced folder
      exit02.vm.synced_folder ".", "/vagrant", disabled: true

      # Run Any Extra Config
      exit02.vm.provision :shell , path: "./helper_scripts/extra_switch_config.sh"

      # Apply the interface re-map
      exit02.vm.provision "file", source: "./helper_scripts/rename_eth_swp", destination: "/home/vagrant/rename_eth_swp"
      exit02.vm.provision "file", source: "./helper_scripts/autogenerated/exit02_remap_eth", destination: "/home/vagrant/remap_eth"
      exit02.vm.provision :shell , inline: "mv /home/vagrant/rename_eth_swp /etc/init.d/rename_eth_swp"
      exit02.vm.provision :shell , inline: "mv /home/vagrant/remap_eth /etc/default/remap_eth"
      exit02.vm.provision :shell , inline: "chmod 755 /etc/init.d/rename_eth_swp"
      exit02.vm.provision :shell , inline: "/etc/init.d/rename_eth_swp verbose"

      exit02.vm.provider "virtualbox" do |vbox|
        vbox.customize ['modifyvm', :id, '--nicpromisc2', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc3', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc4', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc5', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc6', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc7', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc8', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc9', 'allow-vms']
        vbox.customize ['modifyvm', :id, '--nicpromisc10', 'allow-vms']
      end

      # Run Postconfig
      exit02.vm.provision :shell , path: "./helper_scripts/extra_switch_post_config.sh"
  end

end
